// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kiamtofrbbrjohuafzif.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtpYW10b2ZyYmJyam9odWFmemlmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ3MTU4MTAsImV4cCI6MjA3MDI5MTgxMH0.7xUuEnmhXqNYqD4HHyC-oV-iOPZKsip_FaT2oYxTHFs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});